-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.abonelik_planlari (
  id text NOT NULL,
  ad text NOT NULL,
  fiyat numeric NOT NULL,
  sure_gun integer NOT NULL,
  aciklama text,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT abonelik_planlari_pkey PRIMARY KEY (id)
);
CREATE TABLE public.activity_log (
  id text NOT NULL,
  type text NOT NULL,
  plaka text,
  detail text,
  ts timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  firma_id uuid,
  CONSTRAINT activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT activity_log_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.araclar (
  id text NOT NULL,
  plaka text NOT NULL,
  tip text,
  esleme text,
  sofor text,
  telefon text,
  durum text DEFAULT 'Aktif'::text,
  muayene text,
  sigorta text,
  takograf text,
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  firma_id uuid,
  CONSTRAINT araclar_pkey PRIMARY KEY (id),
  CONSTRAINT araclar_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT araclar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.bakim_kayitlari (
  id text NOT NULL,
  user_id uuid NOT NULL,
  arac_id text NOT NULL,
  tarih date NOT NULL,
  tur text NOT NULL,
  aciklama text,
  km numeric,
  maliyet numeric DEFAULT 0,
  sonraki_tarih date,
  sonraki_km numeric,
  servis text,
  created_at timestamp with time zone DEFAULT now(),
  firma_id uuid,
  CONSTRAINT bakim_kayitlari_pkey PRIMARY KEY (id),
  CONSTRAINT bakim_kayitlari_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT bakim_kayitlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.firma_kullanicilar (
  user_id uuid NOT NULL,
  firma_id uuid NOT NULL,
  rol text NOT NULL DEFAULT 'uye'::text,
  CONSTRAINT firma_kullanicilar_pkey PRIMARY KEY (user_id, firma_id),
  CONSTRAINT firma_kullanicilar_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT firma_kullanicilar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.firmalar (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ad text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  deneme_bitis timestamp with time zone,
  abonelik_durumu text DEFAULT 'deneme'::text,
  abonelik_plani text,
  abonelik_bitis timestamp with time zone,
  odeme_ref text,
  max_arac integer DEFAULT 50,
  iletisim_email text,
  telefon text,
  vergi_no text,
  CONSTRAINT firmalar_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_emirleri (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  firma_id uuid,
  user_id uuid NOT NULL,
  musteri_id bigint,
  musteri_adi text,
  arac_plaka text,
  sofor text,
  sofor_tel text,
  konteyner_no text,
  muhur_no text,
  yukle_yeri text,
  teslim_yeri text,
  durum text NOT NULL DEFAULT 'Bekliyor'::text CHECK (durum = ANY (ARRAY['Bekliyor'::text, 'Yolda'::text, 'Fabrikada'::text, 'Teslim Edildi'::text, 'İptal'::text])),
  atama_zamani timestamp with time zone DEFAULT now(),
  yola_zaman timestamp with time zone,
  fabrika_giris timestamp with time zone,
  fabrika_cikis timestamp with time zone,
  teslim_zamani timestamp with time zone,
  fotograflar text DEFAULT '[]'::text,
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  konum_lat double precision,
  konum_lng double precision,
  konum_zaman timestamp with time zone,
  kont_tip text,
  kont_durum text DEFAULT 'Dolu'::text CHECK (kont_durum IS NULL OR (kont_durum = ANY (ARRAY['Dolu'::text, 'Boş'::text]))),
  referans_no text,
  bos_donus text,
  boslama_zaman timestamp with time zone,
  CONSTRAINT is_emirleri_pkey PRIMARY KEY (id),
  CONSTRAINT is_emirleri_firma_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT is_emirleri_user_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT is_emirleri_musteri_fkey FOREIGN KEY (musteri_id) REFERENCES public.musteriler(id)
);
CREATE TABLE public.kayit_log (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  firma_id uuid,
  user_id uuid,
  olay text NOT NULL,
  detay jsonb,
  ip_adresi text,
  ts timestamp with time zone DEFAULT now(),
  CONSTRAINT kayit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.masraflar (
  id text NOT NULL,
  user_id uuid NOT NULL,
  firma_id uuid,
  tarih date NOT NULL,
  arac_id text,
  plaka text,
  kategori text NOT NULL,
  tutar numeric NOT NULL DEFAULT 0,
  makbuz text,
  aciklama text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT masraflar_pkey PRIMARY KEY (id),
  CONSTRAINT masraflar_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT masraflar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.musteriler (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  firma_id uuid NOT NULL,
  user_id uuid NOT NULL,
  firma text NOT NULL,
  yetkili text,
  sektor text DEFAULT 'Diger'::text,
  tel text,
  email text,
  adres text,
  vkn text,
  vade integer DEFAULT 30,
  durum text DEFAULT 'Aktif'::text CHECK (durum = ANY (ARRAY['Aktif'::text, 'Pasif'::text, 'Potansiyel'::text])),
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT musteriler_pkey PRIMARY KEY (id),
  CONSTRAINT musteriler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT musteriler_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.odeme_gecmisi (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  firma_id uuid NOT NULL,
  plan_id text NOT NULL,
  tutar numeric NOT NULL,
  para_birimi text DEFAULT 'TRY'::text,
  durum text DEFAULT 'bekliyor'::text,
  odeme_ref text,
  baslangic timestamp with time zone NOT NULL DEFAULT now(),
  bitis timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  notlar text,
  CONSTRAINT odeme_gecmisi_pkey PRIMARY KEY (id),
  CONSTRAINT odeme_gecmisi_plan_fkey FOREIGN KEY (plan_id) REFERENCES public.abonelik_planlari(id),
  CONSTRAINT odeme_gecmisi_firma_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.seferler (
  id text NOT NULL,
  user_id uuid NOT NULL,
  firma_id uuid,
  tarih date NOT NULL,
  arac_id text,
  plaka text,
  sofor text,
  kalkis text NOT NULL,
  varis text NOT NULL,
  km numeric,
  yuk text,
  ucret numeric DEFAULT 0,
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  ops_id bigint,
  CONSTRAINT seferler_pkey PRIMARY KEY (id),
  CONSTRAINT seferler_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT seferler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT seferler_ops_id_fkey FOREIGN KEY (ops_id) REFERENCES public.is_emirleri(id)
);
CREATE TABLE public.siparisler (
  id text NOT NULL DEFAULT ('SIP-'::text || lpad((nextval('siparisler_seq'::regclass))::text, 4, '0'::text)),
  firma_id uuid NOT NULL,
  user_id uuid NOT NULL,
  musteri_id bigint NOT NULL,
  yukle text NOT NULL,
  teslim text NOT NULL,
  tarih date NOT NULL DEFAULT CURRENT_DATE,
  durum text DEFAULT 'Bekliyor'::text CHECK (durum = ANY (ARRAY['Bekliyor'::text, 'Yolda'::text, 'Teslim Edildi'::text, 'Iptal'::text])),
  tutar numeric DEFAULT 0,
  odeme text DEFAULT 'Bekliyor'::text CHECK (odeme = ANY (ARRAY['Bekliyor'::text, 'Kismi'::text, 'Odendi'::text])),
  yuk text,
  agirlik numeric,
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT siparisler_pkey PRIMARY KEY (id),
  CONSTRAINT siparisler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT siparisler_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT siparisler_musteri_id_fkey FOREIGN KEY (musteri_id) REFERENCES public.musteriler(id)
);
CREATE TABLE public.surucu_belgeler (
  id text NOT NULL,
  user_id uuid NOT NULL,
  firma_id uuid,
  arac_id text,
  ad text NOT NULL,
  tel text,
  ehliyet date,
  src date,
  psiko date,
  created_at timestamp with time zone DEFAULT now(),
  takograf date,
  CONSTRAINT surucu_belgeler_pkey PRIMARY KEY (id),
  CONSTRAINT surucu_belgeler_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT surucu_belgeler_arac_id_fkey FOREIGN KEY (arac_id) REFERENCES public.araclar(id),
  CONSTRAINT surucu_belgeler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.yakit_girisleri (
  id text NOT NULL,
  arac_id text NOT NULL,
  tarih date NOT NULL,
  km numeric NOT NULL,
  litre numeric NOT NULL,
  fiyat numeric DEFAULT 0,
  aciklama text,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  firma_id uuid,
  CONSTRAINT yakit_girisleri_pkey PRIMARY KEY (id),
  CONSTRAINT yakit_girisleri_arac_id_fkey FOREIGN KEY (arac_id) REFERENCES public.araclar(id),
  CONSTRAINT yakit_girisleri_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT yakit_girisleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
